// node --experimental-default-type=module scripts/test_world_conditions.mjs
import assert from "node:assert/strict";
import { WorldClock, formatClock, worldOptions } from "../static/js/sim/world-clock.js";
import { Visibility } from "../static/js/sim/visibility.js";
import { setWeather } from "../static/js/sim/weather.js";

const clock = new WorldClock(23.5, 60);
clock.update(0);
clock.update(60);
assert.equal(clock.hour, 0.5, "accelerated daylight wraps at midnight");
clock.update(60);
assert.equal(clock.hour, 0.5, "paused simulation clock holds daylight");
clock.setRate(1, 120);
assert.equal(clock.hour, 1.5, "changing rate preserves elapsed daylight");
clock.update(180);
assert.ok(Math.abs(clock.hour - (1.5 + 1 / 60)) < 1e-9);
clock.setHour(7, 180);
clock.setRate(0, 180);
clock.update(3600);
assert.equal(clock.hour, 7, "fixed clock ignores elapsed simulation time");
assert.equal(formatClock(23.99999), "23:59");
assert.equal(formatClock(24), "00:00");
assert.equal(formatClock(-0.5), "23:30");
assert.deepEqual(worldOptions(new URLSearchParams("seed=71&traffic=0&clock=60")), { seed: 71, traffic: 0, clockRate: 60 });
assert.deepEqual(worldOptions(new URLSearchParams("seed=bad&traffic=-5&clock=NaN"), 16), { seed: 1, traffic: 16, clockRate: 0 });
assert.equal(worldOptions(new URLSearchParams("traffic=9999")).traffic, 120);

setWeather("dry");
const sight = new Visibility({ pack: { buildings: [] } });
const observer = { x: 0, y: 0, psi: 0 };
assert.equal(sight.range, 80);
assert.ok(sight.canSee(observer, 70, 0));
assert.ok(sight.canSee(observer, 0, 70), "daylight retains peripheral visibility");
sight.setNight(1);
assert.equal(sight.range, 45);
assert.ok(sight.canSee(observer, 40, 0), "low beams illuminate the road ahead");
assert.ok(!sight.canSee(observer, 50, 0));
assert.ok(!sight.canSee(observer, 0, 30), "night limits unlit cross traffic");
assert.ok(sight.canSee(observer, 0, 20));
observer.psi = Math.PI / 2;
assert.ok(sight.canSee(observer, 0, 40), "beam rotates with vehicle heading");
assert.ok(!sight.canSee(observer, 40, 0));
sight.setNight(0.5);
assert.equal(sight.range, 62.5, "twilight changes smoothly");
setWeather("fog");
assert.equal(sight.range, 28, "weather caps the headlight range");
sight.setNight(1);
assert.ok(!sight.canSee(observer, 0, 30));
sight.setNight(NaN);
assert.equal(sight.night, 0);
setWeather("dry");
const blocked = new Visibility({ pack: { buildings: [{ h: 4, pts: [[10, -5], [20, -5], [20, 5], [10, 5]] }] } });
assert.ok(!blocked.canSee({ x: 0, y: 0, psi: 0 }, 30, 0), "headlights do not reveal hazards through buildings");
blocked.setNight(1);
assert.ok(!blocked.canSee({ x: 0, y: 0, psi: 0 }, 30, 0));
globalThis.document = { querySelector: () => null };
const { fixtureWorld } = await import("../static/tests/jev-fixtures.js");
const { buildSnapshot } = await import("../static/js/brain/sensors.js");
const { Vehicle } = await import("../static/js/sim/vehicle.js");
const world = fixtureWorld();
const farCar = new Vehicle(75, 0, 0, 0); farCar.id = "far_car";
world.npcs = [farCar];
const daySnapshot = buildSnapshot(world);
assert.ok(daySnapshot.observed.includes(farCar));
world.visibility.setNight(1);
const nightSnapshot = buildSnapshot(world);
assert.ok(!nightSnapshot.observed.includes(farCar), "night observations hide distant traffic");
assert.equal(nightSnapshot.visibility.range_m, 45);
world.npcs = [];
const nightTarget = buildSnapshot(world).target;
world.visibility.setNight(0);
const dayTarget = buildSnapshot(world).target;
assert.ok(nightTarget.v < dayTarget.v && nightTarget.reasons.includes("limited visibility"), "night sight limits feed the actual driving target");
console.log("World clock, settings and night visibility checks passed");
